# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_components/designs/custom_reminders.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(385, 185)
        Dialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.chk_0_drink_stand = QtWidgets.QCheckBox(Dialog)
        self.chk_0_drink_stand.setGeometry(QtCore.QRect(60, 80, 361, 23))
        self.chk_0_drink_stand.setObjectName("chk_0_drink_stand")
        self.chk_0_eye_relax = QtWidgets.QCheckBox(Dialog)
        self.chk_0_eye_relax.setGeometry(QtCore.QRect(60, 110, 261, 23))
        self.chk_0_eye_relax.setObjectName("chk_0_eye_relax")
        self.chk_0_main_meals = QtWidgets.QCheckBox(Dialog)
        self.chk_0_main_meals.setGeometry(QtCore.QRect(60, 140, 261, 23))
        self.chk_0_main_meals.setObjectName("chk_0_main_meals")
        self.chk_all_habits = QtWidgets.QCheckBox(Dialog)
        self.chk_all_habits.setGeometry(QtCore.QRect(30, 50, 281, 23))
        self.chk_all_habits.setObjectName("chk_all_habits")
        self.lb_title = QtWidgets.QLabel(Dialog)
        self.lb_title.setGeometry(QtCore.QRect(10, 0, 381, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lb_title.setFont(font)
        self.lb_title.setStyleSheet("")
        self.lb_title.setObjectName("lb_title")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(280, 80, 51, 23))
        self.label.setObjectName("label")
        self.ln_interval = QtWidgets.QLineEdit(Dialog)
        self.ln_interval.setGeometry(QtCore.QRect(240, 80, 31, 25))
        self.ln_interval.setAlignment(QtCore.Qt.AlignCenter)
        self.ln_interval.setObjectName("ln_interval")
        self.bt_exit = QtWidgets.QPushButton(Dialog)
        self.bt_exit.setGeometry(QtCore.QRect(340, 10, 30, 30))
        self.bt_exit.setMaximumSize(QtCore.QSize(30, 30))
        self.bt_exit.setStyleSheet("")
        self.bt_exit.setText("")
        self.bt_exit.setFlat(True)
        self.bt_exit.setObjectName("bt_exit")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.chk_0_drink_stand.setText(_translate("Dialog", "Drink && stand up every"))
        self.chk_0_eye_relax.setText(_translate("Dialog", "Eye relaxing"))
        self.chk_0_main_meals.setText(_translate("Dialog", "Breakfast, lunch, dinner"))
        self.chk_all_habits.setText(_translate("Dialog", "All daily habbit"))
        self.lb_title.setText(_translate("Dialog", "Custom reminders"))
        self.label.setText(_translate("Dialog", "hours"))
        self.ln_interval.setText(_translate("Dialog", "1"))
        self.bt_exit.setToolTip(_translate("Dialog", "Close"))
